export const DEFAULT_COLORS = [
	{ name: 'Indian Red', hex: '#CD5C5C' },
	{ name: 'Light Coral Red', hex: '#F08080' },
	{ name: 'Salmon Pink', hex: '#FA8072' },
	{ name: 'Dark Salmon Pink', hex: '#E9967A' },
	{ name: 'Light Salmon Pink', hex: '#FFA07A' },
	{ name: 'Crimson Red', hex: '#DC143C' },
	{ name: 'Red', hex: '#FF0000' },
	{ name: 'Fire Brick Red', hex: '#B22222' },
	{ name: 'Dark Red', hex: '#8B0000' },
	{ name: 'Pink', hex: '#FFC0CB' },
	{ name: 'Light Pink', hex: '#FFB6C1' },
	{ name: 'Hot Pink', hex: '#FF69B4' },
	{ name: 'Deep Pink', hex: '#FF1493' },
	{ name: 'Medium Violet Red', hex: '#C71585' },
	{ name: 'Pale Violet Red', hex: '#DB7093' },
	{ name: 'Light Salmon Pink', hex: '#FFA07A' },
	{ name: 'Coral Orange', hex: '#FF7F50' },
	{ name: 'Tomato Red', hex: '#FF6347' },
	{ name: 'Orange Red', hex: '#FF4500' },
	{ name: 'Dark Orange', hex: '#FF8C00' },
	{ name: 'Orange', hex: '#FFA500' },
	{ name: 'Gold Yellow', hex: '#FFD700' },
	{ name: 'Yellow', hex: '#FFFF00' },
	{ name: 'Light Yellow', hex: '#FFFFE0' },
	{ name: 'Lemon Chiffon Yellow', hex: '#FFFACD' },
	{ name: 'Light Goldenrod Yellow', hex: '#FAFAD2' },
	{ name: 'Papaya Whip Orange', hex: '#FFEFD5' },
	{ name: 'Moccasin Orange', hex: '#FFE4B5' },
	{ name: 'Peach Puff Orange', hex: '#FFDAB9' },
	{ name: 'Pale Goldenrod Yellow', hex: '#EEE8AA' },
	{ name: 'Khaki Yellow', hex: '#F0E68C' },
	{ name: 'Dark Khaki Yellow', hex: '#BDB76B' },
	{ name: 'Lavender Purple', hex: '#E6E6FA' },
	{ name: 'Thistle Purple', hex: '#D8BFD8' },
	{ name: 'Plum Purple', hex: '#DDA0DD' },
	{ name: 'Violet Purple', hex: '#EE82EE' },
	{ name: 'Orchid Purple', hex: '#DA70D6' },
	{ name: 'Fuchsia Purple', hex: '#FF00FF' },
	{ name: 'Magenta Purple', hex: '#FF00FF' },
	{ name: 'Medium Orchid Purple', hex: '#BA55D3' },
	{ name: 'Medium Purple', hex: '#9370DB' },
	{ name: 'Rebecca Purple', hex: '#663399' },
	{ name: 'Blue Violet', hex: '#8A2BE2' },
	{ name: 'Dark Violet Purple', hex: '#9400D3' },
	{ name: 'Dark Orchid Purple', hex: '#9932CC' },
	{ name: 'Dark Magenta Purple', hex: '#8B008B' },
	{ name: 'Purple', hex: '#800080' },
	{ name: 'Indigo Purple', hex: '#4B0082' },
	{ name: 'Slate Blue', hex: '#6A5ACD' },
	{ name: 'Dark Slate Blue', hex: '#483D8B' },
	{ name: 'Medium Slate Blue', hex: '#7B68EE' },
	{ name: 'Green Yellow', hex: '#ADFF2F' },
	{ name: 'Chartreuse Green', hex: '#7FFF00' },
	{ name: 'Lawn Green', hex: '#7CFC00' },
	{ name: 'Lime Green', hex: '#00FF00' },
	{ name: 'Lime Green Alt', hex: '#32CD32' },
	{ name: 'Pale Green', hex: '#98FB98' },
	{ name: 'Light Green', hex: '#90EE90' },
	{ name: 'Medium Spring Green', hex: '#00FA9A' },
	{ name: 'Spring Green', hex: '#00FF7F' },
	{ name: 'Medium Sea Green', hex: '#3CB371' },
	{ name: 'Sea Green', hex: '#2E8B57' },
	{ name: 'Forest Green', hex: '#228B22' },
	{ name: 'Green', hex: '#008000' },
	{ name: 'Dark Green', hex: '#006400' },
	{ name: 'Yellow Green', hex: '#9ACD32' },
	{ name: 'Olive Drab Green', hex: '#6B8E23' },
	{ name: 'Olive Green', hex: '#808000' },
	{ name: 'Dark Olive Green', hex: '#556B2F' },
	{ name: 'Medium Aquamarine Green', hex: '#66CDAA' },
	{ name: 'Dark Sea Green', hex: '#8FBC8B' },
	{ name: 'Light Sea Green', hex: '#20B2AA' },
	{ name: 'Dark Cyan Green', hex: '#008B8B' },
	{ name: 'Teal Green', hex: '#008080' },
	{ name: 'Aqua Cyan', hex: '#00FFFF' },
	{ name: 'Cyan', hex: '#00FFFF' },
	{ name: 'Light Cyan Blue', hex: '#E0FFFF' },
	{ name: 'Pale Turquoise Blue', hex: '#AFEEEE' },
	{ name: 'Aquamarine Blue', hex: '#7FFFD4' },
	{ name: 'Turquoise Blue', hex: '#40E0D0' },
	{ name: 'Medium Turquoise Blue', hex: '#48D1CC' },
	{ name: 'Dark Turquoise Blue', hex: '#00CED1' },
	{ name: 'Cadet Blue', hex: '#5F9EA0' },
	{ name: 'Steel Blue', hex: '#4682B4' },
	{ name: 'Light Steel Blue', hex: '#B0C4DE' },
	{ name: 'Powder Blue', hex: '#B0E0E6' },
	{ name: 'Light Blue', hex: '#ADD8E6' },
	{ name: 'Sky Blue', hex: '#87CEEB' },
	{ name: 'Light Sky Blue', hex: '#87CEFA' },
	{ name: 'Deep Sky Blue', hex: '#00BFFF' },
	{ name: 'Dodger Blue', hex: '#1E90FF' },
	{ name: 'Cornflower Blue', hex: '#6495ED' },
	{ name: 'Medium Slate Blue Alt', hex: '#7B68EE' },
	{ name: 'Royal Blue', hex: '#4169E1' },
	{ name: 'Blue', hex: '#0000FF' },
	{ name: 'Medium Blue', hex: '#0000CD' },
	{ name: 'Dark Blue', hex: '#00008B' },
	{ name: 'Navy Blue', hex: '#000080' },
	{ name: 'Midnight Blue', hex: '#191970' },
	{ name: 'Cornsilk Brown', hex: '#FFF8DC' },
	{ name: 'Blanched Almond Brown', hex: '#FFEBCD' },
	{ name: 'Bisque Brown', hex: '#FFE4C4' },
	{ name: 'Navajo White Brown', hex: '#FFDEAD' },
	{ name: 'Wheat Brown', hex: '#F5DEB3' },
	{ name: 'Burly Wood Brown', hex: '#DEB887' },
	{ name: 'Tan Brown', hex: '#D2B48C' },
	{ name: 'Rosy Brown', hex: '#BC8F8F' },
	{ name: 'Sandy Brown', hex: '#F4A460' },
	{ name: 'Goldenrod Brown', hex: '#DAA520' },
	{ name: 'Dark Goldenrod Brown', hex: '#B8860B' },
	{ name: 'Peru Brown', hex: '#CD853F' },
	{ name: 'Chocolate Brown', hex: '#D2691E' },
	{ name: 'Saddle Brown', hex: '#8B4513' },
	{ name: 'Sienna Brown', hex: '#A0522D' },
	{ name: 'Brown', hex: '#A52A2A' },
	{ name: 'Maroon Brown', hex: '#800000' },
	{ name: 'White', hex: '#FFFFFF' },
	{ name: 'Snow White', hex: '#FFFAFA' },
	{ name: 'Honeydew White', hex: '#F0FFF0' },
	{ name: 'Mint Cream White', hex: '#F5FFFA' },
	{ name: 'Azure White', hex: '#F0FFFF' },
	{ name: 'Alice Blue White', hex: '#F0F8FF' },
	{ name: 'Ghost White', hex: '#F8F8FF' },
	{ name: 'White Smoke', hex: '#F5F5F5' },
	{ name: 'Seashell White', hex: '#FFF5EE' },
	{ name: 'Beige White', hex: '#F5F5DC' },
	{ name: 'Old Lace White', hex: '#FDF5E6' },
	{ name: 'Floral White', hex: '#FFFAF0' },
	{ name: 'Ivory White', hex: '#FFFFF0' },
	{ name: 'Antique White', hex: '#FAEBD7' },
	{ name: 'Linen White', hex: '#FAF0E6' },
	{ name: 'Lavender Blush White', hex: '#FFF0F5' },
	{ name: 'Misty Rose White', hex: '#FFE4E1' },
	{ name: 'Gainsboro Gray', hex: '#DCDCDC' },
	{ name: 'Light Gray', hex: '#D3D3D3' },
	{ name: 'Silver Gray', hex: '#C0C0C0' },
	{ name: 'Dark Gray', hex: '#A9A9A9' },
	{ name: 'Gray', hex: '#808080' },
	{ name: 'Dim Gray', hex: '#696969' },
	{ name: 'Light Slate Gray', hex: '#778899' },
	{ name: 'Slate Gray', hex: '#708090' },
	{ name: 'Dark Slate Gray', hex: '#2F4F4F' },
	{ name: 'Black', hex: '000000' },
];
