export const DEFAULT_COLORS = [
	{ name: 'black', hex: '#000000' },
	{ name: 'purple', hex: '#0D031B' },
	{ name: 'black blue', hex: '#040720' },
	{ name: 'black', hex: '#0C090A' },
	{ name: 'black', hex: '#1C1C1C' },
	{ name: 'dark purple', hex: '#282224' },
	{ name: 'gray', hex: '#34282C' },
	{ name: 'black', hex: '#3B3131' },
	{ name: 'jet black', hex: '#343434' },
	{ name: 'stormy gray', hex: '#3A3B3C' },
	{ name: 'charcoal gray', hex: '#3C4142' },
	{ name: 'light black', hex: '#454545' },
	{ name: 'gray', hex: '#4D4D4F' },
	{ name: 'black', hex: '#413839' },
	{ name: 'gray', hex: '#3D3C3A' },
	{ name: 'black', hex: '#463E3F' },
	{ name: 'black', hex: '#4C4646' },
	{ name: 'gray wolf', hex: '#504A4B' },
	{ name: 'vampire gray', hex: '#565051' },
	{ name: 'iron gray', hex: '#52595D' },
	{ name: 'gray', hex: '#5C5858' },
	{ name: 'carbon gray', hex: '#625D5D' },
	{ name: 'ash gray', hex: '#666362' },
	{ name: 'dimgray', hex: '#696969' },
	{ name: 'nardo gray', hex: '#686A6C' },
	{ name: 'cloudy gray', hex: '#6D6968' },
	{ name: 'smokey gray', hex: '#726E6D' },
	{ name: 'gray', hex: '#736F6E' },
	{ name: 'gray', hex: '#757575' },
	{ name: 'platinum gray', hex: '#797979' },
	{ name: 'gray', hex: '#837E7C' },
	{ name: 'gray', hex: '#808080' },
	{ name: 'battleship gray', hex: '#848482' },
	{ name: 'gray', hex: '#888B90' },
	{ name: 'gray', hex: '#8C8C8C' },
	{ name: 'gunmetal gray', hex: '#8D918D' },
	{ name: 'gray', hex: '#9B9A96' },
	{ name: 'stainless steel gray', hex: '#99A3A3' },
	{ name: 'darkgray', hex: '#A9A9A9' },
	{ name: 'gray', hex: '#A8A9AD' },
	{ name: 'gray', hex: '#B6B6B4' },
	{ name: 'gray', hex: '#B6B6B6' },
	{ name: 'gray', hex: '#C0C0C0' },
	{ name: 'gray', hex: '#C9C1C1' },
	{ name: 'gray', hex: '#C9C0BB' },
	{ name: 'gear steel gray', hex: '#C0C6C7' },
	{ name: 'gray', hex: '#D1D0CE' },
	{ name: 'gray', hex: '#CECECE' },
	{ name: 'lightgray', hex: '#D3D3D3' },
	{ name: 'white', hex: '#DADBDD' },
	{ name: 'gray', hex: '#DCDCDC' },
	{ name: 'light steel gray', hex: '#E0E5E5' },
	{ name: 'white', hex: '#F5F5F5' },
	{ name: 'white gray', hex: '#EEEEEE' },
	{ name: 'gray', hex: '#E5E4E2' },
	{ name: 'gray', hex: '#BCC6CC' },
	{ name: 'blue gray', hex: '#98AFC7' },
	{ name: 'gray', hex: '#838996' },
	{ name: 'lightslategray', hex: '#778899' },
	{ name: 'slategray', hex: '#708090' },
	{ name: 'rat gray', hex: '#6D7B8D' },
	{ name: 'slate granite gray', hex: '#657383' },
	{ name: 'jet gray', hex: '#616D7E' },
	{ name: 'mist blue', hex: '#646D7E' },
	{ name: 'dusty blue', hex: '#6E7F80' },
	{ name: 'steel gray', hex: '#71797E' },
	{ name: 'marble blue', hex: '#566D7E' },
	{ name: 'slate blue gray', hex: '#737CA1' },
	{ name: 'light purple blue', hex: '#728FCE' },
	{ name: 'azure blue', hex: '#4863A0' },
	{ name: 'blue', hex: '#3D5791' },
	{ name: 'blue', hex: '#2F539B' },
	{ name: 'blue', hex: '#2E5090' },
	{ name: 'blue', hex: '#2B547E' },
	{ name: 'charcoal blue', hex: '#36454F' },
	{ name: 'dark blue gray', hex: '#29465B' },
	{ name: 'blue', hex: '#2B3856' },
	{ name: 'deep sea blue', hex: '#123456' },
	{ name: 'blue', hex: '#003366' },
	{ name: 'night blue', hex: '#151B54' },
	{ name: 'midnightblue', hex: '#191970' },
	{ name: 'blue', hex: '#000080' },
	{ name: 'denim dark blue', hex: '#151B8D' },
	{ name: 'darkblue', hex: '#00008B' },
	{ name: 'lapis blue', hex: '#15317E' },
	{ name: 'new midnight blue', hex: '#0000A0' },
	{ name: 'earth blue', hex: '#0000A5' },
	{ name: 'cobalt blue', hex: '#0020C2' },
	{ name: 'mediumblue', hex: '#0000CD' },
	{ name: 'blueberry blue', hex: '#0041C2' },
	{ name: 'canary blue', hex: '#2916F5' },
	{ name: 'blue', hex: '#0000FF' },
	{ name: 'blue', hex: '#0002FF' },
	{ name: 'bright blue', hex: '#0909FF' },
	{ name: 'blue', hex: '#1F45FC' },
	{ name: 'sapphire blue', hex: '#2554C7' },
	{ name: 'blue', hex: '#1569C7' },
	{ name: 'bright navy blue', hex: '#1974D2' },
	{ name: 'balloon blue', hex: '#2B60DE' },
	{ name: 'royalblue', hex: '#4169E1' },
	{ name: 'ocean blue', hex: '#2B65EC' },
	{ name: 'dark sky blue', hex: '#0059FF' },
	{ name: 'blue', hex: '#306EFF' },
	{ name: 'blue', hex: '#157DEC' },
	{ name: 'neon blue', hex: '#1589FF' },
	{ name: 'dodgerblue', hex: '#1E90FF' },
	{ name: 'water blue', hex: '#0E87CC' },
	{ name: 'glacial blue ice', hex: '#368BC1' },
	{ name: 'steelblue', hex: '#4682B4' },
	{ name: 'silk blue', hex: '#488AC7' },
	{ name: 'windows blue', hex: '#357EC7' },
	{ name: 'blue', hex: '#3090C7' },
	{ name: 'cyan blue', hex: '#14A3C7' },
	{ name: 'blue', hex: '#659EC7' },
	{ name: 'columbia blue', hex: '#87AFC7' },
	{ name: 'baby blue', hex: '#95B9C7' },
	{ name: 'cornflowerblue', hex: '#6495ED' },
	{ name: 'sky blue', hex: '#6698FF' },
	{ name: 'blue', hex: '#56A5EC' },
	{ name: 'butterfly blue', hex: '#38ACEC' },
	{ name: 'deepskyblue', hex: '#00BFFF' },
	{ name: 'midday blue', hex: '#3BB9FF' },
	{ name: 'crystal blue', hex: '#5CB3FF' },
	{ name: 'denim blue', hex: '#79BAEC' },
	{ name: 'day sky blue', hex: '#82CAFF' },
	{ name: 'lightskyblue', hex: '#87CEFA' },
	{ name: 'skyblue', hex: '#87CEEB' },
	{ name: 'jeans blue', hex: '#A0CFEC' },
	{ name: 'blue', hex: '#B7CEEC' },
	{ name: 'pastel blue', hex: '#B4CFEC' },
	{ name: 'light day blue', hex: '#ADDFFF' },
	{ name: 'sea blue', hex: '#C2DFFF' },
	{ name: 'heavenly blue', hex: '#C6DEFF' },
	{ name: 'robin egg blue', hex: '#BDEDFF' },
	{ name: 'powderblue', hex: '#B0E0E6' },
	{ name: 'coral blue', hex: '#AFDCEC' },
	{ name: 'lightblue', hex: '#ADD8E6' },
	{ name: 'lightsteelblue', hex: '#B0CFDE' },
	{ name: 'gulf blue', hex: '#C9DFEC' },
	{ name: 'pastel light blue', hex: '#D5D6EA' },
	{ name: 'lavender blue', hex: '#E3E4FA' },
	{ name: 'white blue', hex: '#DBE9FA' },
	{ name: 'purple', hex: '#E6E6FA' },
	{ name: 'blue', hex: '#EBF4FA' },
	{ name: 'white', hex: '#F0F8FF' },
	{ name: 'white', hex: '#F8F8FF' },
	{ name: 'white', hex: '#F0FFFF' },
	{ name: 'blue', hex: '#E0FFFF' },
	{ name: 'blue', hex: '#CCFFFF' },
	{ name: 'electric blue', hex: '#9AFEFF' },
	{ name: 'tron blue', hex: '#7DFDFE' },
	{ name: 'blue', hex: '#57FEFF' },
	{ name: 'blue', hex: '#00FFFF' },
	{ name: 'blue', hex: '#0AFFFF' },
	{ name: 'blue', hex: '#4BF0FC' },
	{ name: 'blue', hex: '#50EBEC' },
	{ name: 'blue diamond', hex: '#4EE2EC' },
	{ name: 'blue', hex: '#16E2F5' },
	{ name: 'blue lagoon', hex: '#8EEBEC' },
	{ name: 'blue', hex: '#AFEEEE' },
	{ name: 'pale blue', hex: '#CFECEC' },
	{ name: 'light blue', hex: '#B3D9D9' },
	{ name: 'tiffany blue', hex: '#81D8D0' },
	{ name: 'blue', hex: '#77BFC7' },
	{ name: 'blue', hex: '#92C7C7' },
	{ name: 'northern lights blue', hex: '#78C7C7' },
	{ name: 'blue green', hex: '#7BCCB5' },
	{ name: 'green', hex: '#66CDAA' },
	{ name: 'aqua seafoam green', hex: '#93E9BE' },
	{ name: 'green', hex: '#AAF0D1' },
	{ name: 'green', hex: '#93FFE8' },
	{ name: 'green', hex: '#7FFFD4' },
	{ name: 'blue', hex: '#40E0D0' },
	{ name: 'blue', hex: '#48D1CC' },
	{ name: 'blue', hex: '#48CCCD' },
	{ name: 'blue', hex: '#46C7C7' },
	{ name: 'blue', hex: '#43C6DB' },
	{ name: 'blue', hex: '#00CED1' },
	{ name: 'macaw blue green', hex: '#43BFC7' },
	{ name: 'lightseagreen', hex: '#20B2AA' },
	{ name: 'seafoam green', hex: '#3EA99F' },
	{ name: 'blue', hex: '#5F9EA0' },
	{ name: 'blue', hex: '#3B9C9C' },
	{ name: 'blue', hex: '#008B8B' },
	{ name: 'teal green', hex: '#00827F' },
	{ name: 'blue', hex: '#008080' },
	{ name: 'teal blue', hex: '#007C80' },
	{ name: 'blue', hex: '#045F5F' },
	{ name: 'blue', hex: '#045D5D' },
	{ name: 'blue', hex: '#033E3E' },
	{ name: 'darkslategray', hex: '#25383C' },
	{ name: 'gray', hex: '#2C3539' },
	{ name: 'blue moss green', hex: '#3C565B' },
	{ name: 'beetle green', hex: '#4C787E' },
	{ name: 'grayish blue', hex: '#5E7D7E' },
	{ name: 'greenish blue', hex: '#307D7E' },
	{ name: 'blue', hex: '#348781' },
	{ name: 'sea turtle green', hex: '#438D80' },
	{ name: 'dull sea green', hex: '#4E8975' },
	{ name: 'dark green blue', hex: '#1F6357' },
	{ name: 'alpine green', hex: '#1B5448' },
	{ name: 'deep sea green', hex: '#306754' },
	{ name: 'bottle green', hex: '#006A4E' },
	{ name: 'medium sea green', hex: '#3CB371' },
	{ name: 'sea green', hex: '#2E8B57' },
	{ name: 'dark green', hex: '#006400' },
	{ name: 'green', hex: '#008000' },
	{ name: 'forest green', hex: '#228B22' },
	{ name: 'green leaf', hex: '#306754' },
	{ name: 'grass green', hex: '#347C2C' },
	{ name: 'olive drab green', hex: '#6B8E23' },
	{ name: 'olive green', hex: '#808000' },
	{ name: 'dark olive green', hex: '#556B2F' },
	{ name: 'camouflage green', hex: '#78866B' },
	{ name: 'sage green', hex: '#848B79' },
	{ name: 'hazel green', hex: '#617C58' },
	{ name: 'fern green', hex: '#667C26' },
	{ name: 'green onion', hex: '#6AA121' },
	{ name: 'moss green', hex: '#ADDFAD' },
	{ name: 'light green', hex: '#90EE90' },
	{ name: 'pale green', hex: '#98FB98' },
	{ name: 'lime green', hex: '#32CD32' },
	{ name: 'neon green', hex: '#00FF00' },
	{ name: 'bright green', hex: '#66FF00' },
	{ name: 'mint green', hex: '#98FF98' },
	{ name: 'green tea', hex: '#B5EAAA' },
	{ name: 'yellow green', hex: '#9ACD32' },
	{ name: 'chartreuse green', hex: '#7FFF00' },
	{ name: 'green apple', hex: '#A2CD5A' },
	{ name: 'mantis green', hex: '#74C365' },
	{ name: 'pear yellow green', hex: '#D1E231' },
	{ name: 'yellow', hex: '#FFFF00' },
	{ name: 'canary yellow', hex: '#FFEF00' },
	{ name: 'gold yellow', hex: '#FFD700' },
	{ name: 'lemon yellow', hex: '#FFF700' },
	{ name: 'sunny yellow', hex: '#FFF380' },
	{ name: 'light yellow', hex: '#FFFFE0' },
	{ name: 'banana yellow', hex: '#FFE135' },
	{ name: 'mustard yellow', hex: '#FFDB58' },
	{ name: 'butter yellow', hex: '#FFFD74' },
	{ name: 'corn yellow', hex: '#E4CD05' },
	{ name: 'khaki yellow', hex: '#F0E68C' },
	{ name: 'pale gold yellow', hex: '#E6BE8A' },
	{ name: 'orange', hex: '#FFA500' },
	{ name: 'deep orange', hex: '#FF8C00' },
	{ name: 'neon orange', hex: '#FF6700' },
	{ name: 'bright orange', hex: '#FF5F00' },
	{ name: 'pumpkin orange', hex: '#F87217' },
	{ name: 'tiger lily orange', hex: '#E55B3C' },
	{ name: 'sunset orange', hex: '#FE6230' },
	{ name: 'tangerine orange', hex: '#E7812E' },
	{ name: 'brown', hex: '#A52A2A' },
	{ name: 'saddle brown', hex: '#8B4513' },
	{ name: 'sienna brown', hex: '#A0522D' },
	{ name: 'muddy brown', hex: '#483C32' },
	{ name: 'chocolate brown', hex: '#2B1B17' },
	{ name: 'coffee brown', hex: '#6F4E37' },
	{ name: 'wood brown', hex: '#966919' },
	{ name: 'tan brown', hex: '#D2B48C' },
	{ name: 'sand brown', hex: '#C2B280' },
	{ name: 'dark brown', hex: '#3D2B1F' },
	{ name: 'sepia brown', hex: '#704214' },
	{ name: 'red', hex: '#FF0000' },
	{ name: 'dark red', hex: '#8B0000' },
	{ name: 'fire engine red', hex: '#F62217' },
	{ name: 'blood red', hex: '#7E3517' },
	{ name: 'cherry red', hex: '#C21E56' },
	{ name: 'ruby red', hex: '#99004C' },
	{ name: 'crimson red', hex: '#DC143C' },
	{ name: 'scarlet red', hex: '#FF2400' },
	{ name: 'tomato red', hex: '#FF6347' },
	{ name: 'coral red', hex: '#FF7F50' },
	{ name: 'indian red', hex: '#CD5C5C' },
	{ name: 'maroon red', hex: '#800000' },
	{ name: 'pink', hex: '#FFC0CB' },
	{ name: 'light pink', hex: '#FFB6C1' },
	{ name: 'hot pink', hex: '#FF69B4' },
	{ name: 'deep pink', hex: '#FF1493' },
	{ name: 'pale violet red', hex: '#DB7093' },
	{ name: 'medium violet red', hex: '#C71585' },
	{ name: 'purple', hex: '#800080' },
	{ name: 'dark purple', hex: '#8B008B' },
	{ name: 'medium purple', hex: '#9370DB' },
	{ name: 'blue purple', hex: '#8A2BE2' },
	{ name: 'dark orchid purple', hex: '#9932CC' },
	{ name: 'dark violet purple', hex: '#9400D3' },
	{ name: 'thistle purple', hex: '#D8BFD8' },
	{ name: 'plum purple', hex: '#DDA0DD' },
	{ name: 'violet purple', hex: '#EE82EE' },
	{ name: 'magenta purple', hex: '#FF00FF' },
	{ name: 'fuchsia purple', hex: '#FF00FF' },
	{ name: 'orchid purple', hex: '#DA70D6' },
	{ name: 'medium orchid purple', hex: '#BA55D3' },
	{ name: 'white', hex: '#FFFFFF' },
	{ name: 'snow white', hex: '#FFFAFA' },
	{ name: 'honeydew white', hex: '#F0FFF0' },
	{ name: 'mint cream white', hex: '#F5FFFA' },
	{ name: 'azure white', hex: '#F0FFFF' },
	{ name: 'alice blue white', hex: '#F0F8FF' },
	{ name: 'ghost white', hex: '#F8F8FF' },
	{ name: 'white smoke', hex: '#F5F5F5' },
	{ name: 'seashell white', hex: '#FFF5EE' },
	{ name: 'beige white', hex: '#F5F5DC' },
	{ name: 'old lace white', hex: '#FDF5E6' },
	{ name: 'floral white', hex: '#FFFFAF' },
	{ name: 'ivory white', hex: '#FFFFF0' },
	{ name: 'antique white', hex: '#FAEBD7' },
	{ name: 'linen white', hex: '#FAF0E6' },
	{ name: 'lavender blush pink', hex: '#FFF0F5' },
	{ name: 'misty rose pink', hex: '#FFE4E1' },
];
